### ISSUE TITLE
❓ AWS::SES::ReceiptRuleSet is missing

### ISSUE THREAD

**Issue by binli0114** [vittorio-nardone/disposable_app#1]
Do you think we can add this resource in the disposable.yml? 

```
ReceiptRuleSet:
      Type: AWS::SES::ReceiptRuleSet
      Properties:
        RuleSetName: !Ref RuleSetName
```
